mysite/urls.py
from django.conf.urls import re_path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from graphene_django.views import GraphQLView
from django.views.decorators.csrf import csrf_exempt


urlpatterns = [
    re_path(r'^', include(('restaurant.urls', 'restaurant'), namespace='restaurant')),
    re_path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^graphql/', csrf_exempt(GraphQLView.as_view(graphiql=True))),

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurant/urls.py
from django.conf.urls import re_path
from . import views


urlpatterns = [
    re_path(r'^getRegion/$', views.getRegion, name='getArea'),
    re_path(r'^getArea/$', views.getArea),
    re_path(r'^api/reviews/$', views.ReviewViewSet.as_view(), name='reviews'),
    re_path(r'^newRestaurant/$', views.restaurant_new, name='restaurant_new'),
    re_path(r'^$', views.restaurant_detail, name='restaurant_detail'),
    re_path(r'^edit/$', views.restaurant_edit, name='restaurant_edit'),
    re_path(r'^newMenu/$', views.menu_new, name='menu_new'),
    re_path(r'^(?P<pk>\d+)/edit/$', views.menu_edit, name='menu_edit'),
    re_path(r'^(?P<pk>\d+)/$', views.menu_detail, name='menu_detail'),
]

restaurant/forms.py
from django import forms
from .models import Restaurant, Menu, MenuCategory
from .widgets import LocationWidget


class RestaurantForm(forms.ModelForm):
    class Meta:
        model = Restaurant
        fields = ['name', 'category', 'address', 'account', 'tel', 'introduction', 'closedDay', 'longitude', 'latitude',
                  'businessLicenseRepresentative', 'businessLicenseMutualName', 'businessLicenseNumber', 'businessHours',
                  'area', 'representative_image', 'representative_menu', 'map_content', 'map_image']
        widgets = {
            'name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': '',
                }
            ),
            'category': forms.Select(
                attrs={
                    'class': 'form-control',
                }
            ),
            'address': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': '',
                }
            ),
            'account': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': '',
                }
            ),
            'tel': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': '',
                }
            ),
            'introduction': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'style': 'height:170px'
                }
            ),
            'closedDay': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': '',
                }
            ),
            'businessLicenseRepresentative': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': '',
                }
            ),
            'businessLicenseMutualName': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': '',
                }
            ),
            'businessLicenseNumber': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': '',
                }
            ),
            'area': forms.Select(
                attrs={
                    'class': 'form-control',
                }
            ),
            'businessHours': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': '',
                }
            ),
            'representative_image': forms.FileInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'representative_menu': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': '',
                }
            ),
        }


class MenuForm(forms.ModelForm):
    class Meta:
        model = Menu
        fields = ['name', 'category', 'price', 'image', 'content', 'soldOut']
        widgets = {
            'name': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'category': forms.Select(
                attrs={
                    'class': 'form-control'
                }
            ),
            'price': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'image': forms.FileInput(
                attrs={
                    'class': 'custom-control-input',
                    'id': 'customFile',
                    'name': 'filename',
                }
            ),
            'content': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'style': 'height: 130px'
                }
            ),
        }

    def __init__(self, admin, restaurant, *args, **kwargs):
        super(MenuForm, self).__init__(*args, **kwargs)
        self.fields['category'].queryset = MenuCategory.objects.filter(admin=admin, restaurant=restaurant)


class MenuCategoryForm(forms.ModelForm):
    class Meta:
        model = MenuCategory
        fields = ['name', 'content']
        widgets = {
            'name': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'content': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'style': 'height: 120px',
                }
            )
        }

restaurant/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import MenuCategory, Menu, Restaurant, Review, Area, Region
from .forms import RestaurantForm, MenuForm, MenuCategoryForm
from django.contrib.auth.decorators import login_required
from .serializers import ReviewSerializer
from rest_framework.views import APIView
from rest_framework.parsers import MultiPartParser, FormParser
from rest_framework.response import Response
from rest_framework import status
import sys
sys.path.append('..')
from admins.models import AdminComment


@login_required
def restaurant_detail(request):
    restaurant = get_object_or_404(Restaurant, admin=request.user)
    menus = Menu.objects.filter(restaurant=restaurant, admin=request.user)
    menu_category = MenuCategory.objects.filter(restaurant=restaurant, admin=request.user)
    menu_count = len(menus)
    reviews = Review.objects.filter(restaurant=restaurant)
    reviews_count = len(reviews)
    admin_comments = AdminComment.objects.filter(restaurant=restaurant, admin=request.user)
    admin_comments_count = len(admin_comments)
    reviews_sum = 0
    reviews_average = 0
    for i in reviews:
        reviews_sum += i.rating
        reviews_average = reviews_sum / reviews_count
        round(reviews_average, 1)
    count = reviews.count()
    like_count = restaurant.likes.count()

    return render(request, 'restaurant/restaurant_detail.html', {
        'restaurant': restaurant,
        'menus': menus,
        'menu_category': menu_category,
        'reviewsCount': count,
        'reviews_average': reviews_average,
        'admin_comments': admin_comments,
        'admin_comments_count': admin_comments_count,
        'menu_count': menu_count,
        'like_count': like_count,
        'reviews': reviews
    })


@login_required
def restaurant_new(request):
    if request.method == 'POST':
        form = RestaurantForm(request.POST, request.FILES)
        if form.is_valid():
            form = form.save(commit=False)
            form.admin = request.user
            form.save()
            return redirect(form)
    else:
        form = RestaurantForm()

    return render(request, 'restaurant/restaurant_new.html', {
        'form': form
    })


@login_required
def restaurant_edit(request):
    restaurant = get_object_or_404(Restaurant, admin=request.user)
    if request.method == 'POST':
        form = RestaurantForm(request.POST, request.FILES, instance=restaurant)
        if form.is_valid():
            form = form.save(commit=False)
            form.admin = request.user
            form.save()
            return redirect(form)
    else:
        form = RestaurantForm(instance=restaurant)

    return render(request, 'restaurant/restaurant_edit.html', {
        'form': form
    })


@login_required
def menu_detail(request, pk):
    menu = get_object_or_404(Menu, pk=pk)
    restaurant = get_object_or_404(Restaurant, admin=request.user)
    return render(request, 'restaurant/menu_detail.html', {
        'menu': menu,
        'restaurant': restaurant
    })


@login_required
def menu_edit(request, pk):
    restaurant = get_object_or_404(Restaurant, admin=request.user)
    menu = get_object_or_404(Menu, pk=pk)
    if request.method == 'POST':
        form = MenuForm(request.POST, request.FILES, instance=menu)
        if form.is_valid():
            form.save()
            return
    else:
        form = MenuForm(request.user, restaurant, instance=menu)

    return render(request, 'restaurant/menu_edit.html', {
        'menu': menu,
        'menu_form': form
    })


@login_required
def menu_new(request):
    restaurant = get_object_or_404(Restaurant, admin=request.user)
    if request.method == 'POST':
        menu_form = MenuForm(request.POST, request.FILES)
        if menu_form.is_valid():
            menu_form = menu_form.save(commit=False)
            menu_form.restaurant = restaurant
            menu_form.save()
            return
    else:
        menu_form = MenuForm(request.user, restaurant)

    return render(request, 'restaurant/menu_new.html', {
        'menu_form': menu_form,
    })


@login_required
def menu_category_new(request):
    restaurant = get_object_or_404(Restaurant, admin=request.user)
    if request.method == 'POST':
        form = MenuCategoryForm(request.POST, request.FILES)
        if form.is_valid():
            form = form.save(commit=False)
            form.admin = request.user
            form.restaurant = restaurant
            form.save()
            return
    else:
        form = MenuCategoryForm(request.user, restaurant)

    return render(request, 'restaurant/menu_category_new.html', {
        'form': form
    })


class ReviewViewSet(APIView):
    pass
    parser_classes = (MultiPartParser, FormParser)

    def get(self, request, *args, **kwargs):
        reviews = Review.objects.all()
        serializer = ReviewSerializer(reviews, many=True)
        return Response(serializer.data)

    def post(self, request, *args, **kwargs):
        reviews_serializer = ReviewSerializer(data=request.data)
        if reviews_serializer.is_valid():
            reviews_serializer.save()
            return Response(reviews_serializer.data, status=status.HTTP_201_CREATED)

        else:
            return Response(reviews_serializer.errors, status=status.HTTP_400_BAD_REQUEST)


def getRegion(request):
    region = ['서울', '경기', '인천', '강원', '제주', '부산', '경남', '대구', '경북', '울산', '대전', '충남', '충북', '광주', '전남', '전북']
    for i in region:
        Region.objects.create(name=i)
    return


def getArea(request):
    region1 = get_object_or_404(Region, name='서울')
    area1 = ['강남·역삼·삼성·논현', '서초·방배', '잠실·신천', '영등포·여의도', '구로·금천·신도림', '강서·화곡·까치산역·목동',
             '천호·길동·둔촌', '서울대·신림·사당·동작', '종로·대학로', '용산·중구·명동·이태원' '성북·도봉·노원', '강북·수유·미아',
             '왕십리·성수', '건대·광진', '동대문·장안·청량리', '중랑·상봉·면목·태릉', '신촌·홍대·서대문·마포', '은평·연신내·불광']
    for i in area1:
        Area.objects.create(name=i, region=region1)

    region2 = get_object_or_404(Region, name='경기')
    area2 = ['수원·인계', '수원시청·권선·영통', '수원역·세류·팔달문·구운·장안', '대부도·제부도', '안성·평택·송탄', '오산·화성·동탄',
             '파주·김포', '고양·일산', '의정부', '부천', '안양·평촌·인덕원·과천', '군포·금정·산본·의왕', '안산', '광명·시흥', '용인',
             '이천·광중·여주', '성남·분당', '구리·남양주·하남', '가평·양평', '양주·동두천·연천·장흥', '포천']
    for i in area2:
        Area.objects.create(name=i, region=region2)

    region3 = get_object_or_404(Region, name='인천')
    area3 = ['부평', '주안', '구월·소래포구', '동암·간석', '중구·월미도·을왕리·인천공항', '작전·경인교대', '용현·숭의·도화·송림', '송도·연수',
             '서구·검단', '강화·옹진·백령도']
    for i in area3:
        Area.objects.create(name=i, region=region3)

    region4 = get_object_or_404(Region, name='강원')
    area4 = ['강릉역·교동택지·옥계', '경포대·사천·주문진', '양양·낙산·하조대·인제', '속초·설악·동명항·고성', '춘천·홍천·철원·화천',
             '원주·횡성', '정동진·동해·삼척', '평창·영월·정선·태백']
    for i in area4:
        Area.objects.create(name=i, region=region4)

    region5 = get_object_or_404(Region, name='제주')
    area5 = ['제주시', '서귀포·마라도']
    for i in area5:
        Area.objects.create(name=i, region=region5)

    region6 = get_object_or_404(Region, name='부산')
    area6 = ['해운대·재송', '송정·기장·정관', '서면·초읍·양정', '연산·토곡', '동래·온천장·부산대·구서·사직', '남포동·부산역·송도·영도·범일동',
             '광안리·수영·경성대·대연·용호', '사상', '덕천·만덕·구포·화명·북구', '강서·하단·사하·명지·신호']
    for i in area6:
        Area.objects.create(name=i, region=region6)

    region7 = get_object_or_404(Region, name='경남')
    area7 = ['김해·장유', '양산·밀양', '거제·통영·고성군', '진주', '사천·남해·하동', '창원 상남·용호·중앙', '창원 명서·팔용·봉곡·북면',
             '마산·진해', '거창·함안·창녕·합천·의령']
    for i in area7:
        Area.objects.create(name=i, region=region7)

    region8 = get_object_or_404(Region, name='대구')
    area8 = ['동성로·시청·서문시장·평리동·비산동', '수성구·남구·수성못', '동대구역·신천·대구공항·동촌', '경북대·북구·칠곡지구',
             '본리·죽전·이월드·두류공원·서부정류장']
    for i in area8:
        Area.objects.create(name=i, region=region8)

    region9 = get_object_or_404(Region, name='경북')
    area9 = ['경주', '구미', '포항 남구', '포항 북구', '울진·울릉도·청송·영덕', '영천·경산·청도', '문경·상주·영주·예천', '안동',
             '김천·성중·칠곡·의성·군위']
    for i in area9:
        Area.objects.create(name=i, region=region9)

    region10 = get_object_or_404(Region, name='울산')
    area10 = ['동구·울주군', '남구·중구·북구']
    for i in area10:
        Area.objects.create(name=i, region=region10)

    region11 = get_object_or_404(Region, name='대전')
    area11 = ['유성 봉명·도안·장대', '중구 은행·대흥·선화·유천', '동구 용전·복합터미널', '대덕구 신탄진·중리', '서구 둔산·용문·월평']
    for i in area11:
        Area.objects.create(name=i, region=region11)

    region12 = get_object_or_404(Region, name='충남')
    area12 = ['천안 서북구', '천안 동남구', '계룡·공주·금산·논산', '아산', '태안·당진·안면도·서산', '서천·부여', '대천·보령', '예산·청양·홍성',
              '세종']
    for i in area12:
        Area.objects.create(name=i, region=region12)

    region13 = get_object_or_404(Region, name='충북')
    area13 = ['청주 흥덕구·서원구', '청주 상당구·청원구', '제천·진천·음성·단양', '충주·수안보', '증평·괴산·영동·보은·옥천']
    for i in area13:
        Area.objects.create(name=i, region=region13)

    region14 = get_object_or_404(Region, name='광주')
    area14 = ['북구', '서구', '동구·남구', '광산구']
    for i in area14:
        Area.objects.create(name=i, region=region14)

    region15 = get_object_or_404(Region, name='전남')
    area15 = ['여수', '순천·광양', '목포·무안·영암', '나주·담양·곡성·구례·영광·장성·함평', '화순·보성·해남·완도·강진·고흥']
    for i in area15:
        Area.objects.create(name=i, region=region15)

    region16 = get_object_or_404(Region, name='전북')
    area16 = ['전주 덕진구', '전주 완산구·완주', '군산', '익산', '남원·임실·진안·무주·순창', '김제·부안·고창·정읍']
    for i in area16:
        Area.objects.create(name=i, region=region16)

    return

restaurant/templates/restaurant/menu_category_new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

restaurant/templates/restaurant/menu_detail.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<div class="container">
    <div class="row mt-4">
        <div class="col-lg-3 col-sm-1 col-md-2 col-xs-0"></div>
        <div class="col-lg-6 col-sm-10 col-md-8 col-xs-12">
            <div style="border:1px solid gray;border-radius:12px;box-shadow: 0px 0px 20px #000;background-color:white;height:760px">
                <div style="background-color: rgb(255,250,250); border-radius:12px 12px;">
                    <div class="row">
                        <div class="col-2 py-2">
                            <a href="{% url 'restaurant:restaurant_detail' %}">
                                <img src="{% static 'image/arrow.png' %}" width="26px">
                            </a>
                        </div>
                        <div class="col-8">
                            <h4 class="text-center py-2 m-0" style="display: block;">{{ restaurant.name }}</h4>
                        </div>
                        <div class="col-2"></div>
                    </div>
                </div>

                <div class="text-center py-5 px-3" style="height:19rem">
                    <img src="{{ menu.image.url }}">
                </div>
                <div class="text-center px-3 py-3" style="background-color: rgb(255,250,250);border-radius: 0px 0px 12px 12px">
                    <h3 style="font-weight: bold">{{ menu.name }}</h3>
                    <hr>
                    <div class="d-flex justify-content-between">
                        <h5 class="m-0">가격</h5>
                        <h5 class="m-0" id="menuPrice"></h5>
                    </div>
                    <hr>
                    <div class="d-flex justify-content-between">
                        <h5 class="my-5">수량</h5>
                        <h5 class="my-5">1개</h5>
                    </div>
                    <div class="d-flex justify-content-between">
                        <h4 class="my-4">총 주문 금액</h4>
                        <h4 class="my-4" id="sumPrice" style="color:rgb(255,48,48);"></h4>
                    </div>
                    <div>
                        <div class="py-2" style="background-color:rgb(236,74,66);border-color:rgb(236,74,66);width:100%;box-shadow: 0px 0px 10px rgb(180,180,180);">
                            <a style="width: 100%;text-decoration:none;color:white" href="{% url 'restaurant:menu_edit' menu.pk %}">
                                <h4 class="my-0 py-2">수정하기</h4>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    function numberWithCommas(x) {
        return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
    }
    document.getElementById("sumPrice").innerHTML = numberWithCommas({{menu.price}})+"원";
    document.getElementById("menuPrice").innerHTML = numberWithCommas({{menu.price}})+"원";

</script>

{% endblock %}

restaurant/templates/restaurant/menu_edit.html
{% extends 'base.html' %}
{% block content %}

{% load static %}
<div class="container">
    <div class="row my-4">
        <div class="col-2"></div>
        <div class="col-8">
            <form action="" method="post" name="menu">
                {% csrf_token %}
                <div class="card" style="border-radius: 12px !important; box-shadow: 0px 0px 20px #000;">
                    <div class="card-header" style="border-top-left-radius: 12px;border-top-right-radius: 12px !important">
                        <h2 class="text-center" style="color:gray">메뉴 등록</h2>
                    </div>
                    <div class="card-body" style="background-color: #FDFDFD">
                        <div class="row mb-3">
                            <div class="col-6">
                                <h5>카테고리</h5>
                                <div class="row">
                                    <div class="col-9 pr-0">
                                        {{ menu_form.category }}
                                    </div>
                                    <div class="col-3">
                                        <div class="row">
                                            <div class="col-6 p-0 text-center" style="height:100%">
                                                <button type="button" class="btn btn-primary" style="background: #FDFDFD;border-color: #FDFDFD">
                                                    <img src="{% static 'image/edit.svg' %}">
                                                </button>
                                            </div>
                                            <div class="col-6 p-0" style="height:100%">
                                                <button type="button" class="btn btn-primary" style="background: #FDFDFD;border-color: #FDFDFD">
                                                    <img src="{% static 'image/add.svg' %}">
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-6">
                                <h5>메뉴 이름</h5>
                                {{ menu_form.name }}
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-6">
                                <h5>가격</h5>
                                {{ menu_form.price }}
                            </div>
                            <div class="col-6">
                                <h5>메뉴 사진</h5>
                                {{ menu_form.image }}
                                <label class="custom-file-label" for="customFile">Choose file</label>
                                <script>
                                    // Add the following code if you want the name of the file appear on select
                                    $(".custom-file-input").on("change", function() {
                                      var fileName = $(this).val().split("\\").pop();
                                      $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
                                    });
                                </script>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-12">
                                <h5>메뉴 소개</h5>
                                {{ menu_form.content }}
                            </div>
                        </div>
                    </div>
                    <div class="card-footer d-flex justify-content-end" style="border-bottom-left-radius: 12px;border-bottom-right-radius: 12px !important">
                        <button type="submit" class="btn btn-primary px-3">등록</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-2">
        </div>
    </div>
</div>


{% endblock %}

restaurant/templates/restaurant/menu_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
<h1>인기메뉴</h1>
{% for i in menu_category %}
    <h1>{{ i }}</h1>
    <div class="row">
    {% for j in menus %}
        {% if j.category == i %}
        <div class="col-2 px-2 pb-2">
            <div class="card p-0">
              <img width="100vw" height="180rem" class="card-img-top" src="{{ j.image.url }}" alt="Card image">
              <div class="card-body row px-3 py-2">
                  <div class="col-6">
                      <h4 class="card-title">{{ j.name }}</h4>
                      <p class="card-text">{{ j.price }}원</p>
                  </div>
                  <div class="col-6 py-1 px-0 row d-flex justify-content-end">
                      <div class="my-2 text-center ">
                        <a href="#" class="btn btn-primary">매진</a>
                        <a href="#" class="btn btn-primary">수정</a>
                      </div>
                  </div>
              </div>
            </div>
        </div>
        {% endif %}
    {% endfor %}
    </div>
{% endfor %}
</div>

{% endblock %}

restaurant/templates/restaurant/menu_new.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<div class="container">
    <div class="row my-4">
        <div class="col-2"></div>
        <div class="col-8">
            <form action="" method="post" name="menu">
                {% csrf_token %}
                <div class="card" style="border-radius: 12px !important; box-shadow: 0px 0px 20px #000;">
                    <div class="card-header" style="border-top-left-radius: 12px;border-top-right-radius: 12px !important">
                        <h2 class="text-center" style="color:gray">메뉴 등록</h2>
                    </div>
                    <div class="card-body" style="background-color: #FDFDFD">
                        <div class="row mb-3">
                            <div class="col-6">
                                <h5>카테고리</h5>
                                <div class="row">
                                    <div class="col-9 pr-0">
                                        {{ menu_form.category }}
                                    </div>
                                    <div class="col-3">
                                        <div class="row">
                                            <div class="col-6 p-0 text-center" style="height:100%">
                                                <button type="button" class="btn btn-primary" style="background: #FDFDFD;border-color: #FDFDFD">
                                                    <img src="{% static 'image/edit.svg' %}">
                                                </button>
                                            </div>
                                            <div class="col-6 p-0" style="height:100%">
                                                <button type="button" class="btn btn-primary" style="background: #FDFDFD;border-color: #FDFDFD">
                                                    <img src="{% static 'image/add.svg' %}">
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-6">
                                <h5>메뉴 이름</h5>
                                {{ menu_form.name }}
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-6">
                                <h5>가격</h5>
                                {{ menu_form.price }}
                            </div>
                            <div class="col-6">
                                <h5>메뉴 사진</h5>
                                {{ menu_form.image }}
                                <label class="custom-file-label" for="customFile">Choose file</label>
                                <script>
                                    // Add the following code if you want the name of the file appear on select
                                    $(".custom-file-input").on("change", function() {
                                      var fileName = $(this).val().split("\\").pop();
                                      $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
                                    });
                                </script>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-12">
                                <h5>메뉴 소개</h5>
                                {{ menu_form.content }}
                            </div>
                        </div>
                    </div>
                    <div class="card-footer d-flex justify-content-end" style="border-bottom-left-radius: 12px;border-bottom-right-radius: 12px !important">
                        <button type="submit" class="btn btn-primary px-3">등록</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-2">
        </div>
    </div>
</div>

{% endblock %}